gather_input_task:
  description: >
    Gather input from the user regarding their business idea, including the problem, solution, UVP (Unique Value Proposition), demographic, and industry.
  expected_output: >
    A structured dataset containing the user input for the business idea, including problem, solution, demographic, and industry.
  agent: controller_agent

reddit_search_task:
  description: >
    Search Reddit for discussions relevant to the provided problem and solution.
  expected_output: >
    A list of Reddit posts that match the query and can be used to understand customer sentiment regarding the provided problem and solution.
  agent: reddit_agent
  context:
    - gather_input_task

twitter_scraping_task:
  description: >
    Scrape Twitter for tweets discussing the user's problem, solution, and potential market.
  expected_output: >
    A collection of tweets related to the user's market or product, showcasing public discussions, sentiment, and customer interest.
  agent: twitter_agent
  context:
    - gather_input_task

generate_report_task:
  description: >
    Analyze the collected data from Reddit and Twitter, and generate a report detailing customer sentiment, market fit, and product viability.
  expected_output: >
    A comprehensive market analysis report based on data from Reddit and Twitter, assessing the need and viability of the user's business idea.
  agent: report_agent
  context:
    - reddit_search_task
    - twitter_scraping_task
